### ISSUE TITLE
AWS EC2 & RDS 설정

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/Tich-Backend#23]
# AWS EC2 & RDS 설정

> AWS EC2 서버 환경과 RDS 데이터베이스 환경을 설정한다.

<br>

### 완료 조건

- [x] AWS EC2 인스턴스를 생성한다.
- [x] EC2 서버에 접속하여 필수 설정을 한다.
      - Java 8 설치
      - 타임존 변경
      - 호스트네임 변경
- [x] AWS RDS 인스턴스를 생성한다.
- [x] 개인 PC에서 RDS에 접속하여 설정 후 테스트를 한다.
- [x] EC2에서 RDS에 접근 확인을한다.

<br> 

## relate to issue
> AWS EC2에 프로젝트 배포 ( #24 )

<br>

> #### Reference
> 책 : 스프링 부트와 AWS로 혼자 구현하는 웹 서비스

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

---

**Comment by vo0a** [comment]
👍👍
