### ISSUE TITLE
AWS EC2에 프로젝트 배포

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/Tich-Backend#24]
# AWS EC2에 프로젝트 배포

> AWS EC2 서버에 이 Repository에 저장된 프로젝트를 배포한다.

<br>

### 완료 조건

- [x] EC2에 프로젝트를 Clone 받는다.
- [x] 배포 스크립트를 작성한다.
- [x] RDS에 테이블을 생성한다.
- [x] 필요한 환경설정을 한다.
- [x] 구글에 EC2 주소를 등록한다.

<br> 

## relate to issue
> AWS EC2 & RDS 설정 ( #23 )

<br>

> #### Reference
> 책 : 스프링 부트와 AWS로 혼자 구현하는 웹 서비스

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

---

**Comment by vo0a** [comment]
👍👍
