### ISSUE TITLE
사용자 도메인 생성

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/Tich-Backend#4]
# 사용자 도메인 생성

> 설계한 데이터베이스를 기반으로 사용자 정보, 기능에 필요한 도메인을 만든다.

<br>

### 완료 조건

- [x] Users의 entity, enum 클래스를 작성한다. 
- [x] DAO로 사용할 JPA Repository 인터페이스를 생성한다.

<br> 

## relate to issue
> Data Base 설계 ( #2 )

<br>

> #### Reference
> 책 : 스프링 부트와 AWS로 혼자 구현하는 웹 서비스

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

---

**Comment by vo0a** [comment]
User에 enum가 필요한 이유가 뭔가요??

**Comment by xyzzeong** [comment]
> User에 enum가 필요한 이유가 뭔가요??

'비회원으로 체험하기'를 고려하여 GUEST와 USER의 권한을 구분하기 위함이었지만,
현재 회원만 사용할 수 있도록 진행한 상태입니다.
그리고 ADMIN 역할도 추가되었습니다.
